  
UTIs:
    _json: &json
        syntax: json
        
    _plist: &plist
        syntax: xml
        preprocessor: /usr/bin/plutil -convert xml1 -o - $targetHL

    _xml: &xml
        syntax: xml
    
    com.adobe.acrobat.sequ: *xml
    dyn.ah62d4rv4ge81g3pvsy: *xml
    
    # .acf
    com.steampowered.appmanifest:
        syntax: txt
    dyn.ah62d4rv4ge80c25g:
        syntax: txt
    
    com.adobe.edn:
        syntax: clojure
    
    com.apple.applescript.script:
        syntax: applescript
        preprocessor: /usr/bin/osadecompile $targetHL
    
    com.apple.dt.document.scheme: *xml    
    com.apple.dt.interfacebuilder.document.storyboard: *xml
    com.apple.interfacebuilder.document.cocoa: *xml
    com.apple.mobileconfig: *xml
    com.apple.property-list: *plist
    com.apple.terminal.settings: *plist
        
    com.apple.terminal.shell-script:
        syntax: shellscript
    
    com.apple.xcode.entitlements-property-list: *plist
    com.apple.xcode.strings-dictionary: *plist
    com.apple.xcode.strings-text: *plist
    
    com.autoit.au3:
        syntax: autoit
    dyn.ah62d4rv4ge80c7mx:
        syntax: autoit
        
    com.barebones.bbedit.ini-configuration:
        syntax: ini
        
    com.barebones.bbedit.typescript-source:
        syntax: typescript
        
    com.bps.elixir-source:
        syntax: elixir
        
    dyn.ah62d4rv4ge80u3pfta:
        syntax: elixir
        
    com.coteditor.scheme:
        syntax: lisp
    
    # .ss
    dyn.ah62d4rv4ge81g62:
        syntax: lisp
    
    # .sls
    dyn.ah62d4rv4ge81g5dx:
        syntax: lisp
    # .sps
    dyn.ah62d4rv4ge81g6dx:
        syntax: lisp
    # .sld
    dyn.ah62d4rv4ge81g5de:
        syntax: lisp
    # .rkt
    dyn.ah62d4rv4ge81e45y:
        syntax: lisp
        
    com.google.earth.kml: *xml
    com.jetbrain.source: *xml
    
    com.macromates.textmate.scheme:
        syntax: lisp
        
    dyn.ah62d4rv4ge80g65usm10y: *xml
    com.microsoft.csproj: *xml
    
    com.microsoft.typescript:
        syntax: typescript
    dyn.ah62d4rv4ge80g7dx:
        syntax: typescript

    com.microsoft.xaml: *xml
            
    com.nutstore.down:
        syntax: md
        
    com.nvidia.cuda:
        syntax: c
    # .cu
    dyn.ah62d4rv4ge80g7k:
        syntax: c
    
    com.seriflabs.xmp: *xml
    dyn.ah62d4rv4ge81u5pu: *xml
    
    com.stata.stata.do:
        syntax: stata
    com.stata.source:
        syntax: stata

    com.sun.java-class:
        syntax: java
        preprocessor: javap -c $targetHL
        extra: --plug-in java_library
        
    com.sun.java-properties:
        syntax: ini
        
    com.sun.java-source:
        syntax: java
        extra: --plug-in java_library

    com.sun.javafx:
        syntax: fx
        
    com.symfony.twig:
        syntax: html
        
    dyn.ah62d4rv4ge81n5xmsv6u:
        syntax: yaml
    com.unity.document:
        syntax: yaml
        
    dev.svelte.source:
        syntax: html
    dyn.ah62d4rv4ge81g7xfrv4gn:
        syntax: html
        
    dev.nix.source:
        syntax: nix
    dyn.ah62d4rv4ge8064p2:
        syntax: nix
        
    io.azkaban.flow:
        syntax: yaml
    dyn.ah62d4rv4ge80q5dts6:
        syntax: yaml

    is.workflow.my.workflow: *plist
    dyn.ah62d4rv4ge81s3xqr75u: *plist

    org.applescript.source:
        syntax: applescript
        preprocessor: /usr/bin/osadecompile $targetHL

    org.arduino.ino-source:
        extra: --plug-in cpp_syslog
        
    org.aruduino.source:
        syntax: c
        
    org.asm.source:
        syntax: assembler
    dyn.ah62d4rv4ge80c65r:
        syntax: assembler
        
    org.bash.source:
        extra: --plug-in bash_functions
        
    org.clojure.script:
        syntax: clojure
        
    dyn.ah62d4rv4ge81k7d2: *xml
    org.fonttools.ttx: *xml
        
    dyn.ah62d4rv4ge8022p3: *xml
    org.mamedev.lay: *xml
        
    org.tug.cls:
        syntax: latex
        
    org.cocoapods.podspec:
        syntax: ruby
        
    org.khronos.gltf: *json
        
    org.json.jsonc: *json
    dyn.ah62d4rv4ge80y65tr3vu: *json
        
    org.jsonlines.jsonl: *json
    dyn.ah62d4rv4ge80y65tr30a: *json
                
    org.microsoft.inf:
        syntax: ini
        
    org.n8gray.lisp:
        syntax: lisp
        
    org.nodejs.cjs:
        syntax: javascript
    dyn.ah62d4rv4ge80g4xx:
        syntax: javascript
        
    org.omg.ecore: *xml
    org.opml.opml: *xml
    org.opml.source: *xml
    dyn.ah62d4rv4ge8086drru: *xml
    
    org.pddl.pddl:
        syntax: lisp
    dyn.ah62d4rv4ge81a3deru:
        syntqx: lisp
        
    org.racket-lang.source:
        syntax: lisp
        
    org.rdf.source: *xml
    
    dyn.ah62d4rv4ge81e62:
        syntax: rust
    
    org.xml-tools.source: *xml
    dyn.ah62d4rv4ge81u6k: *xml
    dyn.ah62d4rv4ge81u7k: *xml
    
    org.xsd.schema: *xml
    dyn.ah62d4rv4ge81u65e: *xml
    org.xul.source: *xml
    
    public.bash-script:
        extra: --plug-in bash_functions
        
    public.c-plus-plus-source:
        extra: --plug-in cpp_syslog
        
    public.c-source:
        extra: --plug-in cpp_syslog
        
    public.data.xml.opml: *xml
    
    public.elixir-source:
        syntax: elixir
    
    public.fortran-95-source:
        syntax: fortran90
    
    public.make-source:
        syntax: makefile
    
    public.objective-c-source:
        syntax: objc
        
    public.properties:
        syntax: ini
        
    public.shell-script:
        extra: --plug-in bash_functions
        
    public.typescript:
        syntax: typescript
        
    public.zsh-script:
        extra: --plug-in bash_functions
        
    dyn.ah62d4rv4ge81g22:
        syntax: scala
    dyn.ah62d4rv4ge81g25brvuu:
        syntax: scala
        
    dyn.ah62d4rv4ge80y652:
        syntax: jsx
        
    dyn.ah62d4rv4ge80w5pq: *xml
    
    dyn.ah62d4rv4ge80c75p:
        syntax: awk
        
    dyn.ah62d4rv4ge80q5xd:
        syntax: sql
    dyn.ah62d4rv4ge81a6xd:
        syntax: sql
    dyn.ah62d4rv4ge81k6xh:
        syntax: sql
    dyn.ah62d4rv4ge81a45x:
        syntax: sql
    dyn.ah62d4rv4ge81a45c:
        syntax: sql
    dyn.ah62d4rv4ge81a25p:
        syntax: sql
    dyn.ah62d4rv4ge81k6dx:
        syntax: sql
    dyn.ah62d4rv4ge81k6dc:
        syntax: sql
    dyn.ah62d4rv4ge81k8pu:
        syntax: sql
    dyn.ah62d4rv4ge81k2pc:
        syntax: sql
    dyn.ah62d4rv4ge80c7xy:
        syntax: sql
    dyn.ah62d4rv4ge80g55s:
        syntax: sql
    dyn.ah62d4rv4ge81g6px:
        syntax: sql
    dyn.ah62d4rv4ge81q72:
        syntax: sql
    dyn.ah62d4rv4ge8047x1:
        syntax: sql
    dyn.ah62d4rv4ge81g6pq:
        syntax: sql
    
    dyn.ah62d4rv4ge81u6pzqz3hw: *xml
    
    dyn.ah62d4rv4ge81g25xsq:
        syntax: scss
        
    dyn.ah62d4rv4ge80s3a:
        syntax: gd
        
    dyn.ah62d4rv4ge80k55drrw1e3xmrvwu:
        syntax: dockerfile
        
    dyn.ah62d4rv4ge80g5pbrrwu:
        syntax: cmake
    
    dyn.ah62d4rv4ge80s52:
        syntax: go
        
    org.fish.source:
        extra: --plug-in bash_functions
        
    dyn.ah62d4rv4ge80s6xbqv0gn:
        syntax: gradle
        
    org.jupyter.ipynb: *json
    # ipynb
    dyn.ah62d4rv4ge80w6d3r3va: *json
        
    org.kmt.source:
        syntax: scala
        
    org.kotlinlang.kotlin-source:
        syntax: kotlin
        
    dyn.ah62d4rv4ge80y5a:
        syntax: julia
        
    dyn.ah62d4rv4ge8007a:
        syntax: kotlin
    
    dyn.ah62d4rv4ge81a8p:
        syntax: py
        preprocessor: uncompyle6 $targetHL
    
    # .bazel
    dyn.ah62d4rv4ge80e2p4qz0a:
        syntax: txt
    # .bzl
    dyn.ah62d4rv4ge80e8xq:
        syntax: txr
    
    # .code-workspace
    dyn.ah62d4rv4ge80g55eqy01s55wrr31a2pdqy: *json
    
    # .cr
    dyn.ah62d4rv4ge80g6u:
        syntax: crystal
        
    #.jsm
    dyn.ah62d4rv4ge80y65r:
        syntax: javascript
    
    # .makefile
    dyn.ah62d4rv4ge8042ppqzxgw5df:
        syntax: makefile
    
    # .mpd
    dyn.ah62d4rv4ge8046de:
        syntax: xml
        
    # .nf
    dyn.ah62d4rv4ge8063u:
        syntax: java
        
    # .pub
    dyn.ah62d4rv4ge81a7pc:
        syntax: txt
        
    # .pyi
    dyn.ah62d4rv4ge81a8pm:
        syntax: python
    # .py3
    dyn.ah62d4rv4ge81a8mx:
        syntax: python
    
    # .sas
    dyn.ah62d4rv4ge81g2px:
        syntax: sas
        
    # smali
    dyn.ah62d4rv4ge81g5pbrvyu:
        syntax: txt
    
    # .t
    dyn.ah62d4rv4ge81k:
        syntax: perl
        
    # .cshtml
    dyn.ah62d4rv4ge80g65ksv002:
        syntax: csharp
        
    org.w3.wsdl:
        syntax: xml
        
    # .wsdl
    dyn.ah62d4rv4ge81s65eru:
        syntax: xml
        
    # .tfvars
    dyn.ah62d4rv4ge81k3x0qf3hg:
        syntax: yaml
    # .tfstate
    dyn.ah62d4rv4ge81k3xxsvu1k3:
        syntax: yaml
    # .tf
    dyn.ah62d4rv4ge81k3u:
        syntax: yaml
    # .hcl
    dyn.ah62d4rv4ge80u25q:
        syntax: yaml
    io.terraform.tfvars:
        syntax: yaml
    
    # .sage
    dyn.ah62d4rv4ge81g2phqy:
        syntax: py
    
    com.sequel-ace.sequel-ace.sql:
        syntax: sql
        
    # .sol
    dyn.ah62d4rv4ge81g55q:
        syntax: sol
    
    #.ado
    dyn.ah62d4rv4ge80c3dt:
        syntax: txt
    #.do
    dyn.ah62d4rv4ge80k52:
        syntax: txt
        
    #.astro
    build.astro.files:
        syntax: jsx
    dyn.ah62d4rv4ge80c65ysm1u:
        syntax: jsx
        
    # lilypond .ly
    org.lilypond.files:
        syntax: ly
    dyn.ah62d4rv4ge8028k:
        syntax: ly
    dyn.ah62d4rv4ge80w5d3:
        syntax: ily
        
    com.adobe.mxml:
        syntax: xml
    dyn.ah62d4rv4ge8048drru:
        syntax: xml
    
    org.raml.raml:
        syntax: yaml
    # .raml
    dyn.ah62d4rv4ge81e2prru:
        syntax: yaml
        
    # .otio
    dyn.ah62d4rv4ge8087dmr6: *json
    
    # .edl
    dyn.ah62d4rv4ge80n3dq:
        syntax: txt
        
    # .mhl
    dyn.ah62d4rv4ge8044dq:
        syntax: txt
    
    # .loctable
    dyn.ah62d4rv4ge80255dsvu0e5df: *plist

        
extensions:
    _json*: &json
        syntax: json
    _plist*: &plist
        syntax: xml
        preprocessor: /usr/bin/plutil -convert xml1 -o - $targetHL

    _xml*: &xml
        syntax: xml
        
    _typescript*: &typescript
        syntax: typescript
    
    acf:
        syntax: txt
        
    ado:
        syntax: txt
    
    au3:
        syntax: autoit
    avt:
        syntax: sql
    a3x:
        syntax: autoit
        
    astro:
        syntax: jsx
    
    bazel:
        syntax: txt
    bzl:
        syntax: txt
        
    code-workspace: *json
    
    cls:
        syntax: latex

    # org.nodejs.cjs, dyn.ah62d4rv4ge80g4xx
    cjs:
        syntax: javascript
        
    con:
        syntax: sql
    
    conf:
        # org.sbarex.conf
        syntax: ini
        
    csproj:
        syntax: xml
        
    cu:
        syntax: c
    
    cr:
        syntax: crystal
        
    cts: *typescript
    
    do:
        syntax: txt
        
    dockerfile:
        syntax: dockerfile
        
    edl:
        syntax: txt
    
    ex:
        syntax: elixir
    exs:
        syntax: elixir
        
    f95:
        syntax: fortran90
    
    # dyn.ah62d4rv4ge80q5dts6
    flow:
        syntax: yaml
        
    fnc:
        syntax: sql
        
    gltf: *json
    
    hcl:
        syntax: yaml
    
    heex:
        syntax: elixir
        
    ily:
        syntax: ly
    
    # dyn.ah62d4rv4ge80w5pq
    iml: *xml
    
    ipynb: *json
       
    #dyn.ah62d4rv4ge80y65r
    jsm:
        syntax: javascript
    
    # dyn.ah62d4rv4ge80y65tr3vu
    jsonc: *json
    jsonl: *json
        
    # dyn.ah62d4rv4ge8007a
    kts:
        syntax: kotlin
    kt:
        syntax: kotlin
        
    #dyn.ah62d4rv4ge80255dsvu0e5df
    loctable: *plist
            
    # dyn.ah62d4rv4ge8044dq
    mhl:
        syntax: txt
    
    mjs:
        syntax: javascript
    
    # dyn.ah62d4rv4ge81u6pzqz3hw:
    ml:
        syntax: ocaml
    mll:
        syntax: ocaml
    mly:
        syntax: ocaml
        
    #dyn.ah62d4rv4ge8046de
    mpd: *xml
        
    mts: *typescript
    
    mvw:
        syntax: sql
        
    mxml: *xml
        
    nf:
        syntax: java
        
    otio: *json
        
    pck:
        syntax: sql
    pkb:
        syntax: sql
    pks:
        syntax: sql
    prc:
        syntax: sql
        
    # org.sbarex.ms-powershell-module-manifest:
    psd1:
        syntax: ps1
    # org.sbarex.ms-powershell-module
    psm1:
        syntax: ps1

    # dyn.ah62d4rv4ge81a7pc
    pub:
        syntax: txt
        
    # org.sbarex.compiled-python-script
    pyc:
        syntax: py
        preprocessor: uncompyle6 $targetHL
        
            
    # dyn.ah62d4rv4ge81a8pm:
    .pyi:
        syntax: python

    # dyn.ah62d4rv4ge81a8mx:
    .py3:
        syntax: python
            
    raml:
        syntax: yaml
    rkt:
        syntax: lisp
        
    sage:
        syntax: py
            
    # dyn.ah62d4rv4ge81g22
    # dyn.ah62d4rv4ge81g25brvuu
    sbt:
        syntax: scala
    
    # dyn.ah62d4rv4ge81g22
    sc:
        syntax: scala
        
    sch:
        syntax: lisp
        
    # dyn.ah62d4rv4ge81g3pvsy
    sequ: *xml
    
    sld:
        syntax: lisp
    sls:
        syntax: lisp
    
    # dyn.ah62d4rv4ge81g5pbrvyu
    smali:
        syntax: txt
        
    sps:
        syntax: lisp
    ss:
        syntax: lisp
        
    sqs:
        syntax: sql
        
    # dyn.ah62d4rv4ge81g7xfrv4gn
    svelte:
        syntax: svelte
        
    t:
        syntax: perl

    tab:
        syntax: sql
                
    tf:
        syntax: yaml
    tfstate:
        syntax: yaml
    tfvars:
        syntax: yaml

    tpb:
        syntax: sql
    tps:
        syntax: sql
    trg:
        syntax: sql
    
    # dyn.ah62d4rv4ge80g7dx:
    ts: *typescript
    tsx: *typescript
    
    typ:
        syntax: sql
        
    unity:
        syntax: yaml
    vw:
        syntax: sql
    
    # dyn.ah62d4rv4ge81s65eru
    wsdl:
        syntax: xml
    
    # dyn.ah62d4rv4ge81u6pzqz3hw
    # dyn.ah62d4rv4ge81u6k
    # dyn.ah62d4rv4ge81u7k
    # dyn.ah62d4rv4ge81u65e
    xsd: *xml
    xquery: *xml
    xq: *xml
    xu: *xml
    
